spring:
  liquibase:
    enabled: true
    check-change-log-location: true
    change-log: db/changelog-cumulative.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://localhost/sandboxDb
    username: SA
    password:
server:
  error:
    whitelabel:
      enabled: false
    path: /